apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: capitalis-ai-dev
  namespace: capitalis
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - dev.capitalis.app
    secretName: capitalis-ai-dev-tls-prod
  rules:
  - host: dev.capitalis.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nuxt-local
            port:
              number: 80
