apiVersion: apps/v1
kind: Deployment
metadata:
  name: capitalis-ai-test
  namespace: capitalis
  labels:
    app: capitalis-ai-test
  annotations:
    kubernetes.io/change-cause: "Update to latest image and port 3000"
    timestamp: "2023-03-08T14:30:00Z"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capitalis-ai-test
  template:
    metadata:
      labels:
        app: capitalis-ai-test
      annotations:
        timestamp: "2023-03-08T14:30:00Z"
    spec:
      containers:
      - name: capitalis-ai-test
        image: nigelrmtaylor/capitalis-ai:master
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: NUXT_HOST
          value: "0.0.0.0"
        - name: NUXT_PORT
          value: "3000"
        - name: NITRO_HOST
          value: "0.0.0.0"
        - name: NITRO_PORT
          value: "3000"
        - name: NUXT_PUBLIC_HANKO_API_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NUXT_PUBLIC_HANKO_API_URL
        - name: VITE_COMMIT_TIME
          value: "2023-12-08T14:30:00Z"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
        startupProbe:
          tcpSocket:
            port: 3000
          failureThreshold: 30
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
