apiVersion: apps/v1
kind: Deployment
metadata:
  name: capitalis-ai
  namespace: capitalis
  labels:
    app: capitalis-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capitalis-ai
  template:
    metadata:
      labels:
        app: capitalis-ai
    spec:
      containers:
      - name: capitalis-ai
        image: nigelrmtaylor/capitalis-ai@sha256:b457a2d8908f5dea112f24c2fbf746758f4da6aadd196268d740b19a523497c9  # Using master tag digest
        ports:
        - containerPort: 4000
        env:
        - name: NODE_ENV
          value: "production"
        - name: NUXT_HOST
          value: "0.0.0.0"
        - name: NUXT_PORT
          value: "4000"
        - name: NITRO_HOST
          value: "0.0.0.0"
        - name: NITRO_PORT
          value: "4000"
        - name: NUXT_PUBLIC_HANKO_API_URL
          value: "https://46f53e73-2fea-4501-a0a4-5b285614b775.hanko.io"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
        startupProbe:
          tcpSocket:
            port: 4000
          failureThreshold: 30
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          tcpSocket:
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 3
        livenessProbe:
          tcpSocket:
            port: 4000
          initialDelaySeconds: 60
          periodSeconds: 20
          failureThreshold: 3
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: capitalis-ai
  namespace: capitalis
spec:
  type: ClusterIP  # Change to ClusterIP if using an Ingress controller
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
  selector:
    app: capitalis-ai
