apiVersion: apps/v1
kind: Deployment
metadata:
  name: capitalis-ai
  namespace: capitalis
  labels:
    app: capitalis-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capitalis-ai
  template:
    metadata:
      labels:
        app: capitalis-ai
    spec:
      containers:
      - name: capitalis-ai
        image: nigelrmtaylor/capitalis-ai:master  # Replace ${DOCKER_USERNAME} with your Docker Hub username
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: NUXT_HOST
          value: "0.0.0.0"
        - name: NUXT_PORT
          value: "3000"
        - name: NITRO_HOST
          value: "0.0.0.0"
        - name: NITRO_PORT
          value: "3000"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
        startupProbe:
          tcpSocket:
            port: 3000
          failureThreshold: 30
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 3
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 20
          failureThreshold: 3
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: capitalis-ai
  namespace: capitalis
spec:
  type: ClusterIP  # Change to ClusterIP if using an Ingress controller
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: capitalis-ai
