apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgraphile-dev-server
  namespace: capitalis
  labels:
    app: postgraphile-dev-server
  annotations:
    kubernetes.io/change-cause: "Update JWT environment variables"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgraphile-dev-server
  template:
    metadata:
      labels:
        app: postgraphile-dev-server
    spec:
      containers:
      - name: postgraphile-dev-server
        image: nigelrmtaylor/capitalis-graphql:master
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: url
        - name: JWKS_URI
          valueFrom:
            secretKeyRef:
              name: jwt-secret-dev
              key: JWKS_URI
        - name: JWT_AUDIENCE
          valueFrom:
            secretKeyRef:
              name: jwt-secret-dev
              key: JWT_AUDIENCE
        - name: GRAPHILE_ENV
          value: development
        - name: ENABLE_GRAPHIQL
          value: "true"
        - name: DEBUG
          value: "@dataplan/pg:PgExecutor:verbose"
        - name: KAFKA_BROKERS
          value: my-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
        ports:
        - containerPort: 5678
        livenessProbe:
          tcpSocket:
            port: 5678
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 5678
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
