name: Docker Build and Publish

on:
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: capitalis-ai
  VITE_APP_VERSION: ${{ github.ref_name }}
  VITE_GIT_COMMIT: ${{ github.sha }}
  NUXT_PUBLIC_ONESIGNAL_REST_API_KEY: ${{ secrets.NUXT_PUBLIC_ONESIGNAL_REST_API_KEY }}
  NUXT_PUBLIC_HANKO_API_URL: ${{ secrets.NUXT_PUBLIC_HANKO_API_URL }}
  GRAPHQL_URL: ${{ secrets.GRAPHQL_URL }}
  GRAPHQL_WS_URL: ${{ secrets.GRAPHQL_WS_URL }}
  NOTIFICATION_SERVER_URL: ${{ secrets.NOTIFICATION_SERVER_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set build timestamp
        id: timestamp
        run: echo "BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=master,enable=${{ github.ref == 'refs/heads/master' }}
            type=raw,value=${{ github.sha }},enable=${{ github.ref == 'refs/heads/master' }}
            type=raw,value=${{ github.ref_name }},enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VITE_APP_VERSION=${{ github.ref_name }}
            VITE_COMMIT_TIME=${{ env.BUILD_TIME }}
            VITE_GIT_COMMIT=${{ github.sha }}
            NUXT_PUBLIC_ONESIGNAL_REST_API_KEY=${{ secrets.NUXT_PUBLIC_ONESIGNAL_REST_API_KEY }}
            NUXT_PUBLIC_HANKO_API_URL=${{ secrets.NUXT_PUBLIC_HANKO_API_URL }}
            GRAPHQL_URL=${{ secrets.GRAPHQL_URL }}
            GRAPHQL_WS_URL=${{ secrets.GRAPHQL_WS_URL }}
            NOTIFICATION_SERVER_URL=${{ secrets.NOTIFICATION_SERVER_URL }}
